### ISSUE TITLE
frontend: fix cut off tooltip

### ISSUE THREAD

**Issue by magicjascha** [magicjascha/fuse_shift#33]
use bootstrap https://www.w3schools.com/bootstrap/bootstrap_tooltip.asp
(all?) helptext-css-classes (custom tooltip) can be deleted

**Comment by magicjascha** [comment]
![image](https://user-images.githubusercontent.com/34845153/50789381-5a523780-12bc-11e9-86cf-799378d13f2d.png)

**Comment by AstiV** [comment]
Please check pull request #40 for the solution to this issue
